# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'myui.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1248, 791)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 10, 1201, 711))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(360, 40, 821, 301))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.mLb = QtWidgets.QLabel(self.gridLayoutWidget)
        self.mLb.setText("")
        self.mLb.setAlignment(QtCore.Qt.AlignCenter)
        self.mLb.setObjectName("mLb")
        self.gridLayout.addWidget(self.mLb, 1, 0, 1, 1)
        self.pLb = QtWidgets.QLabel(self.gridLayoutWidget)
        self.pLb.setText("")
        self.pLb.setAlignment(QtCore.Qt.AlignCenter)
        self.pLb.setObjectName("pLb")
        self.gridLayout.addWidget(self.pLb, 1, 1, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 0, 0, 1, 2)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(360, 370, 821, 301))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.line_3 = QtWidgets.QFrame(self.gridLayoutWidget_2)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_2.addWidget(self.line_3, 0, 0, 1, 2)
        self.pfLb = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.pfLb.setText("")
        self.pfLb.setAlignment(QtCore.Qt.AlignCenter)
        self.pfLb.setObjectName("pfLb")
        self.gridLayout_2.addWidget(self.pfLb, 1, 1, 1, 1)
        self.mfLb = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.mfLb.setText("")
        self.mfLb.setAlignment(QtCore.Qt.AlignCenter)
        self.mfLb.setObjectName("mfLb")
        self.gridLayout_2.addWidget(self.mfLb, 1, 0, 1, 1)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(360, 10, 821, 31))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 1, 1, 1)
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(360, 340, 821, 31))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 0, 1, 1, 1)
        self.idftBn = QtWidgets.QPushButton(self.tab)
        self.idftBn.setGeometry(QtCore.QRect(210, 20, 80, 24))
        self.idftBn.setObjectName("idftBn")
        self.dftBn = QtWidgets.QPushButton(self.tab)
        self.dftBn.setGeometry(QtCore.QRect(60, 20, 80, 24))
        self.dftBn.setObjectName("dftBn")
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(20, 100, 311, 271))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.oriLb = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.oriLb.setText("")
        self.oriLb.setAlignment(QtCore.Qt.AlignCenter)
        self.oriLb.setObjectName("oriLb")
        self.gridLayout_5.addWidget(self.oriLb, 1, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.gridLayoutWidget_5)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_5.addWidget(self.line, 0, 0, 1, 1)
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(20, 400, 311, 271))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.idftLb = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.idftLb.setText("")
        self.idftLb.setAlignment(QtCore.Qt.AlignCenter)
        self.idftLb.setObjectName("idftLb")
        self.gridLayout_6.addWidget(self.idftLb, 1, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.gridLayoutWidget_6)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_6.addWidget(self.line_2, 0, 0, 1, 1)
        self.gridLayoutWidget_7 = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(20, 70, 311, 31))
        self.gridLayoutWidget_7.setObjectName("gridLayoutWidget_7")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.gridLayoutWidget_7)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.oriLb_3 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.oriLb_3.setAlignment(QtCore.Qt.AlignCenter)
        self.oriLb_3.setObjectName("oriLb_3")
        self.gridLayout_7.addWidget(self.oriLb_3, 0, 0, 1, 1)
        self.gridLayoutWidget_8 = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget_8.setGeometry(QtCore.QRect(20, 370, 311, 31))
        self.gridLayoutWidget_8.setObjectName("gridLayoutWidget_8")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.gridLayoutWidget_8)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.oriLb_4 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.oriLb_4.setAlignment(QtCore.Qt.AlignCenter)
        self.oriLb_4.setObjectName("oriLb_4")
        self.gridLayout_8.addWidget(self.oriLb_4, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayoutWidget_9 = QtWidgets.QWidget(self.tab_2)
        self.gridLayoutWidget_9.setGeometry(QtCore.QRect(20, 180, 1161, 481))
        self.gridLayoutWidget_9.setObjectName("gridLayoutWidget_9")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.gridLayoutWidget_9)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.outputLb = QtWidgets.QLabel(self.gridLayoutWidget_9)
        self.outputLb.setText("")
        self.outputLb.setAlignment(QtCore.Qt.AlignCenter)
        self.outputLb.setObjectName("outputLb")
        self.gridLayout_9.addWidget(self.outputLb, 0, 1, 1, 1)
        self.inputLb = QtWidgets.QLabel(self.gridLayoutWidget_9)
        self.inputLb.setText("")
        self.inputLb.setAlignment(QtCore.Qt.AlignCenter)
        self.inputLb.setObjectName("inputLb")
        self.gridLayout_9.addWidget(self.inputLb, 0, 0, 1, 1)
        self.gridLayoutWidget_10 = QtWidgets.QWidget(self.tab_2)
        self.gridLayoutWidget_10.setGeometry(QtCore.QRect(20, 10, 811, 132))
        self.gridLayoutWidget_10.setObjectName("gridLayoutWidget_10")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.gridLayoutWidget_10)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_10.addWidget(self.label_7, 2, 4, 1, 1)
        self.cutoffSb = QtWidgets.QSpinBox(self.gridLayoutWidget_10)
        self.cutoffSb.setObjectName("cutoffSb")
        self.gridLayout_10.addWidget(self.cutoffSb, 0, 2, 1, 6)
        self.GauHighBn = QtWidgets.QPushButton(self.gridLayoutWidget_10)
        self.GauHighBn.setObjectName("GauHighBn")
        self.gridLayout_10.addWidget(self.GauHighBn, 4, 4, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_10.addWidget(self.label_6, 2, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_10.addWidget(self.label_8, 0, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_10.addWidget(self.label_12, 3, 6, 1, 1)
        self.HSb = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_10)
        self.HSb.setObjectName("HSb")
        self.gridLayout_10.addWidget(self.HSb, 2, 7, 1, 1)
        self.idHighBn = QtWidgets.QPushButton(self.gridLayoutWidget_10)
        self.idHighBn.setObjectName("idHighBn")
        self.gridLayout_10.addWidget(self.idHighBn, 4, 0, 1, 1)
        self.homoBn = QtWidgets.QPushButton(self.gridLayoutWidget_10)
        self.homoBn.setObjectName("homoBn")
        self.gridLayout_10.addWidget(self.homoBn, 4, 6, 1, 2)
        self.GauLowBn = QtWidgets.QPushButton(self.gridLayoutWidget_10)
        self.GauLowBn.setObjectName("GauLowBn")
        self.gridLayout_10.addWidget(self.GauLowBn, 3, 4, 1, 1)
        self.bLowBn = QtWidgets.QPushButton(self.gridLayoutWidget_10)
        self.bLowBn.setObjectName("bLowBn")
        self.gridLayout_10.addWidget(self.bLowBn, 3, 2, 1, 1)
        self.LSb = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_10)
        self.LSb.setObjectName("LSb")
        self.gridLayout_10.addWidget(self.LSb, 3, 7, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.gridLayoutWidget_10)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_10.addWidget(self.line_5, 2, 1, 3, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_10.addWidget(self.label_11, 2, 6, 1, 1)
        self.idLowBn = QtWidgets.QPushButton(self.gridLayoutWidget_10)
        self.idLowBn.setObjectName("idLowBn")
        self.gridLayout_10.addWidget(self.idLowBn, 3, 0, 1, 1)
        self.line_7 = QtWidgets.QFrame(self.gridLayoutWidget_10)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout_10.addWidget(self.line_7, 1, 0, 1, 8)
        self.line_6 = QtWidgets.QFrame(self.gridLayoutWidget_10)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout_10.addWidget(self.line_6, 2, 3, 3, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_10.addWidget(self.label_5, 2, 0, 1, 1)
        self.bHighBn = QtWidgets.QPushButton(self.gridLayoutWidget_10)
        self.bHighBn.setObjectName("bHighBn")
        self.gridLayout_10.addWidget(self.bHighBn, 4, 2, 1, 1)
        self.line_13 = QtWidgets.QFrame(self.gridLayoutWidget_10)
        self.line_13.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.gridLayout_10.addWidget(self.line_13, 2, 5, 3, 1)
        self.gridLayoutWidget_11 = QtWidgets.QWidget(self.tab_2)
        self.gridLayoutWidget_11.setGeometry(QtCore.QRect(20, 150, 1161, 31))
        self.gridLayoutWidget_11.setObjectName("gridLayoutWidget_11")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.gridLayoutWidget_11)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_11)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_12.addWidget(self.label_9, 0, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget_11)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_12.addWidget(self.label_10, 0, 1, 1, 1)
        self.line_11 = QtWidgets.QFrame(self.gridLayoutWidget_11)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.gridLayout_12.addWidget(self.line_11, 1, 0, 1, 1)
        self.line_12 = QtWidgets.QFrame(self.gridLayoutWidget_11)
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.gridLayout_12.addWidget(self.line_12, 1, 1, 1, 1)
        self.gridLayoutWidget_13 = QtWidgets.QWidget(self.tab_2)
        self.gridLayoutWidget_13.setGeometry(QtCore.QRect(840, 10, 163, 81))
        self.gridLayoutWidget_13.setObjectName("gridLayoutWidget_13")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.gridLayoutWidget_13)
        self.gridLayout_15.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.TSb = QtWidgets.QSpinBox(self.gridLayoutWidget_13)
        self.TSb.setObjectName("TSb")
        self.gridLayout_15.addWidget(self.TSb, 0, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget_13)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_15.addWidget(self.label_15, 0, 0, 1, 1)
        self.motionBlurBn = QtWidgets.QPushButton(self.gridLayoutWidget_13)
        self.motionBlurBn.setObjectName("motionBlurBn")
        self.gridLayout_15.addWidget(self.motionBlurBn, 1, 0, 1, 2)
        self.gridLayoutWidget_14 = QtWidgets.QWidget(self.tab_2)
        self.gridLayoutWidget_14.setGeometry(QtCore.QRect(1010, 10, 171, 121))
        self.gridLayoutWidget_14.setObjectName("gridLayoutWidget_14")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.gridLayoutWidget_14)
        self.gridLayout_16.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget_14)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_16.addWidget(self.label_16, 0, 0, 1, 1)
        self.WeinerBn = QtWidgets.QPushButton(self.gridLayoutWidget_14)
        self.WeinerBn.setObjectName("WeinerBn")
        self.gridLayout_16.addWidget(self.WeinerBn, 1, 0, 1, 2)
        self.invBn = QtWidgets.QPushButton(self.gridLayoutWidget_14)
        self.invBn.setObjectName("invBn")
        self.gridLayout_16.addWidget(self.invBn, 2, 0, 1, 2)
        self.kSb = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_14)
        self.kSb.setDecimals(4)
        self.kSb.setObjectName("kSb")
        self.gridLayout_16.addWidget(self.kSb, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1248, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen_File = QtWidgets.QAction(MainWindow)
        self.actionOpen_File.setObjectName("actionOpen_File")
        self.menuFile.addAction(self.actionOpen_File)
        self.menubar.addAction(self.menuFile.menuAction())

        self.cutoffSb.setRange(1, 255)
        self.cutoffSb.setSingleStep(1)
        self.cutoffSb.setValue(10)

        self.HSb.setRange(0, 255)
        self.HSb.setSingleStep(0.1)
        self.HSb.setValue(5.0)

        self.LSb.setRange(0, 255)
        self.LSb.setSingleStep(0.1)
        self.LSb.setValue(1.0)

        self.TSb.setRange(0, 300)
        self.TSb.setSingleStep(1)
        self.TSb.setValue(30)

        self.kSb.setRange(0, 1)
        self.kSb.setSingleStep(0.0001)
        self.kSb.setValue(0.001)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Magnitude without f"))
        self.label_2.setText(_translate("MainWindow", "Phase Angle without f"))
        self.label_3.setText(_translate("MainWindow", "Magnitude with f"))
        self.label_4.setText(_translate("MainWindow", "Phase Angle with f"))
        self.idftBn.setText(_translate("MainWindow", "iDFT"))
        self.dftBn.setText(_translate("MainWindow", "DFT"))
        self.oriLb_3.setText(_translate("MainWindow", "Input image"))
        self.oriLb_4.setText(_translate("MainWindow", "Inverse DFT image"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Magnitude And Phase Angel"))
        self.label_7.setText(_translate("MainWindow", "Gaussian"))
        self.GauHighBn.setText(_translate("MainWindow", "Highpass"))
        self.label_6.setText(_translate("MainWindow", "Butterworth"))
        self.label_8.setText(_translate("MainWindow", "Cut-off Frequency"))
        self.label_12.setText(_translate("MainWindow", "Gamma L"))
        self.idHighBn.setText(_translate("MainWindow", "Highpass"))
        self.homoBn.setText(_translate("MainWindow", "Homomorphic"))
        self.GauLowBn.setText(_translate("MainWindow", "Lowpass"))
        self.bLowBn.setText(_translate("MainWindow", "Lowpass"))
        self.label_11.setText(_translate("MainWindow", "Gamma H"))
        self.idLowBn.setText(_translate("MainWindow", "Lowpass"))
        self.label_5.setText(_translate("MainWindow", "Ideal Filter"))
        self.bHighBn.setText(_translate("MainWindow", "Highpass"))
        self.label_9.setText(_translate("MainWindow", "Input image"))
        self.label_10.setText(_translate("MainWindow", "Output image"))
        self.label_15.setText(_translate("MainWindow", "T"))
        self.motionBlurBn.setText(_translate("MainWindow", "Motion Blur"))
        self.label_16.setText(_translate("MainWindow", "K"))
        self.WeinerBn.setText(_translate("MainWindow", "Wiener Filter"))
        self.invBn.setText(_translate("MainWindow", "Inverse Filter"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Processing Frequency Domain"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen_File.setText(_translate("MainWindow", "Open File"))
