# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'myui.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1044, 741)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 301, 141))
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 281, 101))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.RGBPb = QtWidgets.QPushButton(self.layoutWidget)
        self.RGBPb.setObjectName("RGBPb")
        self.gridLayout.addWidget(self.RGBPb, 0, 0, 1, 1)
        self.CMYPb = QtWidgets.QPushButton(self.layoutWidget)
        self.CMYPb.setObjectName("CMYPb")
        self.gridLayout.addWidget(self.CMYPb, 0, 1, 1, 1)
        self.HSIPb = QtWidgets.QPushButton(self.layoutWidget)
        self.HSIPb.setObjectName("HSIPb")
        self.gridLayout.addWidget(self.HSIPb, 0, 2, 1, 1)
        self.XYZPb = QtWidgets.QPushButton(self.layoutWidget)
        self.XYZPb.setObjectName("XYZPb")
        self.gridLayout.addWidget(self.XYZPb, 1, 0, 1, 1)
        self.LabPb = QtWidgets.QPushButton(self.layoutWidget)
        self.LabPb.setObjectName("LabPb")
        self.gridLayout.addWidget(self.LabPb, 1, 1, 1, 1)
        self.YUVPb = QtWidgets.QPushButton(self.layoutWidget)
        self.YUVPb.setObjectName("YUVPb")
        self.gridLayout.addWidget(self.YUVPb, 1, 2, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 160, 500, 500))
        self.groupBox_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.inputLb = QtWidgets.QLabel(self.groupBox_2)
        self.inputLb.setGeometry(QtCore.QRect(20, 30, 460, 460))
        self.inputLb.setAlignment(QtCore.Qt.AlignCenter)
        self.inputLb.setObjectName("inputLb")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(530, 160, 500, 500))
        self.groupBox_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_3.setObjectName("groupBox_3")
        self.outputLb = QtWidgets.QLabel(self.groupBox_3)
        self.outputLb.setGeometry(QtCore.QRect(20, 30, 460, 460))
        self.outputLb.setAlignment(QtCore.Qt.AlignCenter)
        self.outputLb.setObjectName("outputLb")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(330, 10, 391, 141))
        self.groupBox_4.setObjectName("groupBox_4")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_4)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 30, 371, 108))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.springRb = QtWidgets.QRadioButton(self.layoutWidget1)
        self.springRb.setObjectName("springRb")
        self.gridLayout_2.addWidget(self.springRb, 0, 0, 1, 1)
        self.rainbowRb = QtWidgets.QRadioButton(self.layoutWidget1)
        self.rainbowRb.setObjectName("rainbowRb")
        self.gridLayout_2.addWidget(self.rainbowRb, 0, 2, 1, 1)
        self.autumnRb = QtWidgets.QRadioButton(self.layoutWidget1)
        self.autumnRb.setObjectName("autumnRb")
        self.gridLayout_2.addWidget(self.autumnRb, 0, 1, 1, 1)
        self.summerRb = QtWidgets.QRadioButton(self.layoutWidget1)
        self.summerRb.setObjectName("summerRb")
        self.gridLayout_2.addWidget(self.summerRb, 1, 0, 1, 1)
        self.twilightRb = QtWidgets.QRadioButton(self.layoutWidget1)
        self.twilightRb.setObjectName("twilightRb")
        self.gridLayout_2.addWidget(self.twilightRb, 1, 3, 1, 1)
        self.hotRb = QtWidgets.QRadioButton(self.layoutWidget1)
        self.hotRb.setObjectName("hotRb")
        self.gridLayout_2.addWidget(self.hotRb, 1, 2, 1, 1)
        self.coolRb = QtWidgets.QRadioButton(self.layoutWidget1)
        self.coolRb.setObjectName("coolRb")
        self.gridLayout_2.addWidget(self.coolRb, 0, 3, 1, 1)
        self.winterRb = QtWidgets.QRadioButton(self.layoutWidget1)
        self.winterRb.setObjectName("winterRb")
        self.gridLayout_2.addWidget(self.winterRb, 1, 1, 1, 1)
        self.cmapLb = QtWidgets.QLabel(self.layoutWidget1)
        self.cmapLb.setAlignment(QtCore.Qt.AlignCenter)
        self.cmapLb.setObjectName("cmapLb")
        self.gridLayout_2.addWidget(self.cmapLb, 2, 0, 1, 4)
        self.pseudoPb = QtWidgets.QPushButton(self.layoutWidget1)
        self.pseudoPb.setObjectName("pseudoPb")
        self.gridLayout_2.addWidget(self.pseudoPb, 3, 1, 1, 2)
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(740, 10, 291, 141))
        self.groupBox_5.setObjectName("groupBox_5")
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox_5)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 30, 271, 106))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.kmeanSd = QtWidgets.QSlider(self.layoutWidget2)
        self.kmeanSd.setOrientation(QtCore.Qt.Horizontal)
        self.kmeanSd.setObjectName("kmeanSd")
        self.gridLayout_3.addWidget(self.kmeanSd, 0, 0, 1, 4)
        self.kmeanPb = QtWidgets.QPushButton(self.layoutWidget2)
        self.kmeanPb.setObjectName("kmeanPb")
        self.gridLayout_3.addWidget(self.kmeanPb, 3, 1, 1, 2)
        self.kLb = QtWidgets.QLabel(self.layoutWidget2)
        self.kLb.setAlignment(QtCore.Qt.AlignCenter)
        self.kLb.setObjectName("kLb")
        self.gridLayout_3.addWidget(self.kLb, 1, 0, 1, 4)
        self.pB = QtWidgets.QProgressBar(self.centralwidget)
        self.pB.setGeometry(QtCore.QRect(10, 680, 1021, 23))
        self.pB.setProperty("value", 0)
        self.pB.setObjectName("pB")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1044, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menuBar)
        self.actionOpen_File = QtWidgets.QAction(MainWindow)
        self.actionOpen_File.setObjectName("actionOpen_File")
        self.menuFile.addAction(self.actionOpen_File)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.groupButton = QtWidgets.QButtonGroup(MainWindow)
        self.groupButton.addButton(self.springRb, 7)
        self.groupButton.addButton(self.summerRb, 6)
        self.groupButton.addButton(self.autumnRb, 0)
        self.groupButton.addButton(self.winterRb, 3)
        self.groupButton.addButton(self.rainbowRb, 4)
        self.groupButton.addButton(self.hotRb,11) 
        self.groupButton.addButton(self.coolRb, 8)
        self.groupButton.addButton(self.twilightRb, 18)
        
        self.kmeanSd.setRange(2,10)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Color Transformation"))
        self.RGBPb.setText(_translate("MainWindow", "RGB"))
        self.CMYPb.setText(_translate("MainWindow", "CMY"))
        self.HSIPb.setText(_translate("MainWindow", "HSI"))
        self.XYZPb.setText(_translate("MainWindow", "XYZ"))
        self.LabPb.setText(_translate("MainWindow", "L*a*b"))
        self.YUVPb.setText(_translate("MainWindow", "YUV"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Input"))
        self.inputLb.setText(_translate("MainWindow", "Input"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Output"))
        self.outputLb.setText(_translate("MainWindow", "output"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Pseudo Color"))
        self.springRb.setText(_translate("MainWindow", "Spring"))
        self.rainbowRb.setText(_translate("MainWindow", "Rainbow"))
        self.autumnRb.setText(_translate("MainWindow", "Autumn"))
        self.summerRb.setText(_translate("MainWindow", "Summer"))
        self.twilightRb.setText(_translate("MainWindow", "Twilight"))
        self.hotRb.setText(_translate("MainWindow", "Hot"))
        self.coolRb.setText(_translate("MainWindow", "Cool"))
        self.winterRb.setText(_translate("MainWindow", "Winter"))
        self.cmapLb.setText(_translate("MainWindow", "CMAP"))
        self.pseudoPb.setText(_translate("MainWindow", "Pseudo Color"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Kmeans"))
        self.kmeanPb.setText(_translate("MainWindow", "Kmeans"))
        self.kLb.setText(_translate("MainWindow", "K = 2"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen_File.setText(_translate("MainWindow", "Open File"))
