# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'myui.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1013, 550)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.imgLb_out = QtWidgets.QLabel(self.centralwidget)
        self.imgLb_out.setGeometry(QtCore.QRect(640, 70, 351, 361))
        self.imgLb_out.setFrameShape(QtWidgets.QFrame.Box)
        self.imgLb_out.setFrameShadow(QtWidgets.QFrame.Plain)
        self.imgLb_out.setText("")
        self.imgLb_out.setAlignment(QtCore.Qt.AlignCenter)
        self.imgLb_out.setObjectName("imgLb_out")
        self.imgLb = QtWidgets.QLabel(self.centralwidget)
        self.imgLb.setGeometry(QtCore.QRect(270, 70, 351, 361))
        self.imgLb.setFrameShape(QtWidgets.QFrame.Box)
        self.imgLb.setFrameShadow(QtWidgets.QFrame.Plain)
        self.imgLb.setText("")
        self.imgLb.setAlignment(QtCore.Qt.AlignCenter)
        self.imgLb.setObjectName("imgLb")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(780, 20, 67, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(386, 20, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.proB = QtWidgets.QProgressBar(self.centralwidget)
        self.proB.setGeometry(QtCore.QRect(270, 450, 721, 23))
        self.proB.setProperty("value", 0)
        self.proB.setObjectName("proB")
        self.textB = QtWidgets.QTextBrowser(self.centralwidget)
        self.textB.setGeometry(QtCore.QRect(10, 400, 244, 91))
        self.textB.setObjectName("textB")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 244, 371))
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 221, 311))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.gridLayoutWidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(25)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(25)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(True)
        self.tableWidget.verticalHeader().setDefaultSectionSize(25)
        self.gridLayout.addWidget(self.tableWidget, 1, 0, 1, 2)
        self.sizesB = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.sizesB.setAlignment(QtCore.Qt.AlignCenter)
        self.sizesB.setObjectName("sizesB")
        self.gridLayout.addWidget(self.sizesB, 0, 1, 1, 1)
        self.sfPb = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.sfPb.setObjectName("sfPb")
        self.gridLayout.addWidget(self.sfPb, 3, 0, 1, 2)
        self.cB = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.cB.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cB.setObjectName("cB")
        self.gridLayout.addWidget(self.cB, 2, 0, 1, 2)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.tab_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 221, 89))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 1, 1, 1)
        self.zeroSl = QtWidgets.QSlider(self.gridLayoutWidget_2)
        self.zeroSl.setOrientation(QtCore.Qt.Horizontal)
        self.zeroSl.setObjectName("zeroSl")
        self.gridLayout_2.addWidget(self.zeroSl, 1, 0, 1, 2)
        self.edgePb = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.edgePb.setObjectName("edgePb")
        self.gridLayout_2.addWidget(self.edgePb, 2, 0, 1, 2)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.tab_2)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 120, 221, 216))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.minPb = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.minPb.setObjectName("minPb")
        self.gridLayout_3.addWidget(self.minPb, 11, 0, 1, 2)
        self.midPb = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.midPb.setObjectName("midPb")
        self.gridLayout_3.addWidget(self.midPb, 9, 0, 1, 2)
        self.maxPb = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.maxPb.setObjectName("maxPb")
        self.gridLayout_3.addWidget(self.maxPb, 10, 0, 1, 2)
        self.LaplaPb = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.LaplaPb.setObjectName("LaplaPb")
        self.gridLayout_3.addWidget(self.LaplaPb, 4, 0, 1, 2)
        self.sizesB_2 = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.sizesB_2.setAlignment(QtCore.Qt.AlignCenter)
        self.sizesB_2.setObjectName("sizesB_2")
        self.gridLayout_3.addWidget(self.sizesB_2, 1, 1, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.gridLayoutWidget_3)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_3.addWidget(self.line_2, 0, 0, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 1, 0, 1, 1)
        self.gussPb = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.gussPb.setObjectName("gussPb")
        self.gridLayout_3.addWidget(self.gussPb, 5, 0, 1, 2)
        self.SobelPb = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.SobelPb.setObjectName("SobelPb")
        self.gridLayout_3.addWidget(self.SobelPb, 6, 0, 1, 2)
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1013, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen_File = QtWidgets.QAction(MainWindow)
        self.actionOpen_File.setObjectName("actionOpen_File")
        self.menuFile.addAction(self.actionOpen_File)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Output"))
        self.label_2.setText(_translate("MainWindow", "Original"))
        self.label_4.setText(_translate("MainWindow", "Mask Size"))
        self.sfPb.setText(_translate("MainWindow", "Set Filter"))
        self.cB.setText(_translate("MainWindow", "Average Coefficient"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.label_5.setText(_translate("MainWindow", "Zero Crossing Threshold"))
        self.label_7.setText(_translate("MainWindow", "0"))
        self.edgePb.setText(_translate("MainWindow", "Laplacian of Gaussian"))
        self.minPb.setText(_translate("MainWindow", "Min Filter"))
        self.midPb.setText(_translate("MainWindow", "Median Filter"))
        self.maxPb.setText(_translate("MainWindow", "Max Filter"))
        self.LaplaPb.setText(_translate("MainWindow", "Laplacain"))
        self.label_6.setText(_translate("MainWindow", "Mask Size"))
        self.gussPb.setText(_translate("MainWindow", "Gaussian"))
        self.SobelPb.setText(_translate("MainWindow", "Sobel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen_File.setText(_translate("MainWindow", "Open File"))
