# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'myui.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1013, 614)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.imgLb_out = QtWidgets.QLabel(self.centralwidget)
        self.imgLb_out.setGeometry(QtCore.QRect(640, 70, 351, 361))
        self.imgLb_out.setAlignment(QtCore.Qt.AlignCenter)
        self.imgLb_out.setObjectName("imgLb_out")
        self.imgLb = QtWidgets.QLabel(self.centralwidget)
        self.imgLb.setGeometry(QtCore.QRect(260, 70, 351, 361))
        self.imgLb.setAlignment(QtCore.Qt.AlignCenter)
        self.imgLb.setObjectName("imgLb")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(780, 20, 67, 17))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(400, 20, 67, 17))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.proB = QtWidgets.QProgressBar(self.centralwidget)
        self.proB.setGeometry(QtCore.QRect(250, 540, 741, 23))
        self.proB.setProperty("value", 24)
        self.proB.setObjectName("proB")
        self.edgePb = QtWidgets.QPushButton(self.centralwidget)
        self.edgePb.setGeometry(QtCore.QRect(20, 350, 91, 25))
        self.edgePb.setObjectName("edgePb")
        self.sizesB = QtWidgets.QSpinBox(self.centralwidget)
        self.sizesB.setGeometry(QtCore.QRect(20, 50, 48, 26))
        self.sizesB.setObjectName("sizesB")
        self.sfPb = QtWidgets.QPushButton(self.centralwidget)
        self.sfPb.setGeometry(QtCore.QRect(100, 50, 91, 24))
        self.sfPb.setObjectName("sfPb")
        self.textB = QtWidgets.QTextBrowser(self.centralwidget)
        self.textB.setGeometry(QtCore.QRect(250, 450, 741, 71))
        self.textB.setObjectName("textB")
        self.midPb = QtWidgets.QPushButton(self.centralwidget)
        self.midPb.setGeometry(QtCore.QRect(20, 470, 91, 24))
        self.midPb.setObjectName("midPb")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(20, 90, 221, 231))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.maxPb = QtWidgets.QPushButton(self.centralwidget)
        self.maxPb.setGeometry(QtCore.QRect(20, 500, 91, 24))
        self.maxPb.setObjectName("maxPb")
        self.minPb = QtWidgets.QPushButton(self.centralwidget)
        self.minPb.setGeometry(QtCore.QRect(20, 530, 91, 24))
        self.minPb.setObjectName("minPb")
        self.gussPb = QtWidgets.QPushButton(self.centralwidget)
        self.gussPb.setGeometry(QtCore.QRect(20, 440, 91, 24))
        self.gussPb.setObjectName("gussPb")
        self.LaplaPb = QtWidgets.QPushButton(self.centralwidget)
        self.LaplaPb.setGeometry(QtCore.QRect(20, 410, 91, 24))
        self.LaplaPb.setObjectName("LaplaPb")
        self.cB = QtWidgets.QCheckBox(self.centralwidget)
        self.cB.setGeometry(QtCore.QRect(210, 50, 86, 22))
        self.cB.setObjectName("cB")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1013, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen_File = QtWidgets.QAction(MainWindow)
        self.actionOpen_File.setObjectName("actionOpen_File")
        self.menuFile.addAction(self.actionOpen_File)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.imgLb_out.setText(_translate("MainWindow", "output"))
        self.imgLb.setText(_translate("MainWindow", "input"))
        self.label_3.setText(_translate("MainWindow", "Update"))
        self.label_2.setText(_translate("MainWindow", "Origin"))
        self.edgePb.setText(_translate("MainWindow", "LoG"))
        self.sfPb.setText(_translate("MainWindow", "Set Filter"))
        self.midPb.setText(_translate("MainWindow", "Median Filter"))
        self.maxPb.setText(_translate("MainWindow", "Max Filter"))
        self.minPb.setText(_translate("MainWindow", "Min Filter"))
        self.gussPb.setText(_translate("MainWindow", "Guss Filter"))
        self.LaplaPb.setText(_translate("MainWindow", "Laplacain"))
        self.cB.setText(_translate("MainWindow", "CheckBox"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen_File.setText(_translate("MainWindow", "Open File"))
